# Generated by Django 5.2.8 on 2026-01-26 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_created_at_alter_product_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='updated_at',
            new_name='modified_at',
        ),
    ]
