# Generated by Django 5.2.8 on 2026-01-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_buy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('is_login', models.BooleanField(default=True)),
            ],
        ),
    ]
