# Generated by Django 5.2.8 on 2026-01-26 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='discount',
        ),
    ]
