# Generated by Django 5.2.8 on 2026-01-26 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0004_remove_sale_discount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sale',
            new_name='Sell',
        ),
    ]
