# Generated by Django 5.2.8 on 2026-01-27 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0005_rename_sale_sell'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buy',
            old_name='unit_price',
            new_name='buying_price',
        ),
    ]
