# Generated by Django 5.2.8 on 2025-12-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.IntegerField(choices=[(0, 'Business Owner'), (1, 'Storage manager'), (2, 'Sales man')], default=2),
            preserve_default=False,
        ),
    ]
