# Generated by Django 5.2.8 on 2026-01-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_user_fisherman'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fisherman',
            name='id',
        ),
        migrations.AlterField(
            model_name='fisherman',
            name='email',
            field=models.EmailField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
