# Generated by Django 5.2.8 on 2026-01-26 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_fisherman_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fisherman',
            old_name='updated_at',
            new_name='modified_at',
        ),
    ]
